# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data


##########
# URL settings 
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://jak487.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /example_repository
# repository is the github repository's full url
repository: https://github.com/jak487/example_repository


##########
# Site settings
#
# title of site appears in banner
title: example title
# tagline appears in banner
tagline: example tagline
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "example description"


####### Leave the Below As Is ########

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown

